In [1]:
# numpy library imported
import numpy as np  
  
# random matrices are generated and printed
A = np.random.randint(10, size=(3,3))
B = np.random.randint(10, size=(3,3))

print(f"Matrix A:\n {A}\n")
print(f"Matrix B:\n {B}\n")

# matrix C, as a product of matrices A and B is generated
C = np.matmul(A,B)
print(f"Matrix A x B = C [with np.matmul]:\n {C}\n")

#alternatively_1;

D=A@B

print(f"Matrix A x B = C [with @]:\n {D}\n")

#alternatively_2;

E=np.dot(A,B)

print(f"Matrix A x B = C [with np.dot]:\n {E}\n")

Matrix A:
 [[2 5 7]
 [2 3 6]
 [1 8 5]]

Matrix B:
 [[8 1 5]
 [9 7 6]
 [1 3 9]]

Matrix A x B = C [with np.matmul]:
 [[ 68  58 103]
 [ 49  41  82]
 [ 85  72  98]]

Matrix A x B = C [with @]:
 [[ 68  58 103]
 [ 49  41  82]
 [ 85  72  98]]

Matrix A x B = C [with np.dot]:
 [[ 68  58 103]
 [ 49  41  82]
 [ 85  72  98]]

